mysql:
  image: hypriot/rpi-mysql
  volumes:
    - "./volume/mysql:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  build: ./compose/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=password
  links:
    - mysql
  ports:
     - 8080:80
  volumes:
     - "./volume/phpmyadmin/sessions:/sessions"
