mysql:
  image: hypriot/rpi-mysql
  volumes:
    - "./volume/mysql:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=password
  ports:
    - 3306

phpmyadmin:
  build: ./compose/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=password
  links:
    - mysql
  ports:
     - 8080:80
  volumes:
     - "./volume/phpmyadmin/sessions:/sessions"

node:
  build: ./compose/node
  devices:
    - "/dev/gpiomem:/dev/gpiomem"
    - "/dev/i2c-1:/dev/i2c-1"
  ports:
    - 1880:1880
  tty: true
