version: "3.5"

services:
  mysql:
    image: hypriot/rpi-mysql
    volumes:
      - "./volume/mysql:/var/lib/mysql"
      - "./compose/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      #MYSQL_DATABASE: temp
      #MYSQL_USER: tempuser
      #MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password
      TZ : Asia/Tokyo
    ports:
      - 3306
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  phpmyadmin:
    build: ./compose/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - "./volume/phpmyadmin/sessions:/sessions"
    networks:
      app_net:
        ipv4_address: 172.30.0.3


  node-red:
    #image: nodered/node-red:latest
    build: ./compose/node
    environment:
      - TZ=Aisa/Tokyo
    ports:
      - 1880:1880
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - ./volume/node/node-red-data:/data
    networks:
      app_net:
        ipv4_address: 172.30.0.4



#node:
#  build: ./compose/node
#  devices:
#    - "/dev/gpiomem:/dev/gpiomem"
#    - "/dev/i2c-1:/dev/i2c-1"
#  ports:
#    - 1880:1880
#  tty: true

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
