mysql:
  image: hypriot/rpi-mysql
  volumes:
    - "./volume/mysql:/var/lib/mysql"
    #- "./compose/mysql/init:/docker-entrypoint-initdb.d"
  environment:
    MYSQL_DATABASE: temp
    MYSQL_USER: tempuser
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
    TZ : Asia/Tokyo
  ports:
    - 3306:3306

phpmyadmin:
  build: ./compose/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=password
  links:
    - mysql
  ports:
     - 8080:80
  volumes:
     - "./volume/phpmyadmin/sessions:/sessions"

node-red:
  #image: nodered/node-red:latest
  build: ./compose/node
  environment:
    - TZ=Aisa/Tokyo
  ports:
    - "1880:1880"
  devices:
    - "/dev/gpiomem:/dev/gpiomem"
    - "/dev/i2c-1:/dev/i2c-1"
# #networks:
  #  - node-red-net
  volumes:
    - ./volume/node/node-red-data:/data


#node:
#  build: ./compose/node
#  devices:
#    - "/dev/gpiomem:/dev/gpiomem"
#    - "/dev/i2c-1:/dev/i2c-1"
#  ports:
#    - 1880:1880
#  tty: true
