CREATE DATABASE IF NOT EXISTS temp;
CREATE USER 'tempuser'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON temp.* to tempuser@'%';
USE temp;
CREATE TABLE IF NOT EXISTS temp (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,sensorid INT,value FLOAT);



